**参考资料：[pytorch官方文档](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)**

# Tensor入门
## Tensors

In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[9.0315e+30, 4.5618e-41, 9.0315e+30],
        [4.5618e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.5019e+28],
        [1.7406e+25, 4.0604e+18, 6.1630e-33],
        [4.6316e+27, 1.1287e+27, 1.7390e+25]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.0548, 0.1626, 0.3968],
        [0.5115, 0.9604, 0.5717],
        [0.5196, 0.0010, 0.4317],
        [0.4606, 0.5829, 0.3154],
        [0.3733, 0.6064, 0.5924]])


In [4]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.0493, 0.7234, 0.1995],
        [0.4149, 0.1741, 0.9843],
        [0.0372, 0.6960, 0.3112],
        [0.7528, 0.8825, 0.5493],
        [0.5794, 0.5679, 0.8664]])


In [7]:
print(x.size())

torch.Size([5, 3])


torch.Size is in fact a tuple, so it supports all tuple operations.

## Operations

In [8]:
y = torch.rand(5,3)
print(x + y)

tensor([[0.0877, 1.4738, 0.2816],
        [0.6152, 0.3392, 1.2994],
        [0.9182, 1.2767, 0.7799],
        [1.3721, 1.5400, 1.4937],
        [0.6277, 0.7177, 1.3231]])


In [9]:
print(torch.add(x,y))

tensor([[0.0877, 1.4738, 0.2816],
        [0.6152, 0.3392, 1.2994],
        [0.9182, 1.2767, 0.7799],
        [1.3721, 1.5400, 1.4937],
        [0.6277, 0.7177, 1.3231]])


In [10]:
# 也可以加入一个output tensor
result = torch.rand(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.0877, 1.4738, 0.2816],
        [0.6152, 0.3392, 1.2994],
        [0.9182, 1.2767, 0.7799],
        [1.3721, 1.5400, 1.4937],
        [0.6277, 0.7177, 1.3231]])


In [11]:
# 在位计算  in-place
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x
y.add_(x)
print(y)

tensor([[0.0877, 1.4738, 0.2816],
        [0.6152, 0.3392, 1.2994],
        [0.9182, 1.2767, 0.7799],
        [1.3721, 1.5400, 1.4937],
        [0.6277, 0.7177, 1.3231]])


In [12]:
# 索引和numpy类似
print(x)
print(x[:,1])

tensor([[0.0493, 0.7234, 0.1995],
        [0.4149, 0.1741, 0.9843],
        [0.0372, 0.6960, 0.3112],
        [0.7528, 0.8825, 0.5493],
        [0.5794, 0.5679, 0.8664]])
tensor([0.7234, 0.1741, 0.6960, 0.8825, 0.5679])


In [13]:
# Use torch.view resize/reshape tensor
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) #-1代表根据其他维的大小计算得到
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# If you have a one element tensor, use .item() to get the value as a Python number
# 用.item()把一个tensor转换为Python自带的数字类型
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1326])
-0.13263453543186188


## 和numpy的转换

In [15]:
# 把一个torch tensor转换为numpy array
a = torch.ones(3,3)
b = a.numpy()
print(a)
print(b)
# 这种方式的转化两者共享内存，即一个变化了另一个也变化
a.add_(torch.ones(3,3))
print(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [16]:
# 把一个numpy array转换为torch tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)
# 同样地，两者共享内存
np.add(a,1,out=a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
# 注意，numpy的数据的size一般都是一个元组，torch的数据size不需要输入元组
print(np.ones((3,3)))
print(torch.ones(3,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


所有在CPU上的Tensor(除了CharTensor)都支持和numpy的相互转换

## CUDA Tensors

In [18]:
if torch.cuda.is_available:
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)  # directly create a tensor on GPU
    x = x.to(device)  # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))   # ``.to`` can also change dtype together!

tensor([0.8674], device='cuda:0')
tensor([0.8674], dtype=torch.float64)


In [19]:
torch.cuda.is_available()

True

In [20]:
import time

In [22]:
x = torch.randn(10000,10000)
y = torch.randn(10000,10000)

start_time = time.clock()
z1 = torch.mul(x,y)
end_time = time.clock()
print(end_time-start_time)

x1 = x.cuda()
y1 = y.cuda()
start_time = time.clock()
z1 = torch.mul(x1,y1)
end_time = time.clock()
print(end_time-start_time)

0.4673609999999986
0.020020000000000593


# [Autograd](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html)
autograd包是所有神经网络的核心。

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

torch.Tensor is the central class of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it. When you finish your computation you can call .backward() and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.

To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.

To prevent tracking history (and using memory), you can also wrap the code block in with torch.no_grad():. This can be particularly helpful when evaluating a model because the model may have trainable parameters with requires_grad=True, but for which we don’t need the gradients.

There’s one more class which is very important for autograd implementation - a Function.

Tensor and Function are interconnected and build up an acyclic graph, that encodes a complete history of computation. Each tensor has a .grad_fn attribute that references a Function that has created the Tensor (except for Tensors created by the user - their grad_fn is None).

If you want to compute the derivatives, you can call .backward() on a Tensor. If Tensor is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to backward(), however if it has more elements, you need to specify a gradient argument that is a tensor of matching shape.

In [23]:
# Create a tensor and set requires_grad=True to track computation with it
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [24]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [25]:
# y was created as a result of an operation, so it has a grad_fn.
print(y.grad_fn)
print(y.grad)

None


In [26]:
z = y * y * 3
out = z.mean()
print(z, out)
print(z.grad_fn)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [27]:
# .requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. 
#The input flag defaults to False if not given.
a = torch.randn(2,2)
a = ((a * 3)/(a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## Gradients

In [28]:
# Let’s backprop now. Because out contains a single scalar, 
# out.backward() is equivalent to out.backward(torch.tensor(1.)).
out.backward()

In [29]:
print(x.grad)  # Print gradients d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [30]:
# another case
temp_1 = torch.randn(1,requires_grad=True)
temp_2 = temp_1 * 3 + 1
temp_2.backward()
print(temp_2.grad)

None


In [31]:
# another case
temp_1 = torch.randn(1,requires_grad=True)
temp_2 = temp_1 * temp_1*3 + 1
temp_2.backward()
print(temp_2.grad)

None


In [32]:
from torch.autograd import Variable
x = Variable(torch.ones(2,3), requires_grad = True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [33]:
y = x + 2
z = y * y * 5
out = z.mean()
#z.backward() #出错，RuntimeError: grad can be implicitly created only for scalar outputs
out.backward()
print(out)
print(x.grad)
# 多次运行该段程序，x.grad会每次增大5，out不变。为什么？

tensor(45., grad_fn=<MeanBackward1>)
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [34]:
x = Variable(torch.ones(1), requires_grad = True)
print(x)

tensor([1.], requires_grad=True)


In [35]:
y = x + 2
z = y * y * 5
out = z.mean()
#z.backward() #出错，RuntimeError: grad can be implicitly created only for scalar outputs
out.backward()
print(out)
print(x.grad)
# 多次运行该段程序，x.grad会每次增大30，out不变。

tensor(45., grad_fn=<MeanBackward1>)
tensor([30.])


**PyTorch 0.4开始，torch.autograd.Variable和torch.Tensor现在是同一类**

In [36]:
x = torch.ones(2,3, requires_grad = True)
print(x)
y = x + 2
z = y * y * 5
out = z.mean()
out.backward()
print(out)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor(45., grad_fn=<MeanBackward1>)
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [37]:
print(type(x))
print(x.type())
print(isinstance(x,float))
print(isinstance(x,torch.FloatTensor))

<class 'torch.Tensor'>
torch.FloatTensor
False
True


In [38]:
x = torch.tensor([1])
y = 2
z = x.item() + y   # .item()可以把一个tensor转换为正常的Python数字
print(z)

3


In [39]:
a = list(0 for i in range(10))

In [40]:
a[1] = 10
a

[0, 10, 0, 0, 0, 0, 0, 0, 0, 0]

In [41]:
b = [0 for i in range(10)]
b[0] = b[0] + 1
b

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]