In [2]:
import torch
import numpy as np

In [50]:
x = torch.empty(5, 4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
x = torch.zeros(5, 4, dtype=torch.int16)
x

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int16)

In [47]:
x = torch.rand(4, 3, 2)
x

tensor([[[0.1874, 0.2360],
         [0.9065, 0.1175],
         [0.4255, 0.1101]],

        [[0.3431, 0.0756],
         [0.0137, 0.6598],
         [0.6495, 0.9332]],

        [[0.7644, 0.6045],
         [0.1288, 0.7307],
         [0.4130, 0.2217]],

        [[0.8319, 0.8982],
         [0.1355, 0.3529],
         [0.2234, 0.7068]]])

In [64]:
x = torch.ones([3, 4])
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
x = torch.tensor([[4, 3, 8], 
                [9, 5, 1], 
                [2, 7, 6]])
print(x)

tensor([[4, 3, 8],
        [9, 5, 1],
        [2, 7, 6]])


In [59]:
x.size()

torch.Size([3, 3])

In [67]:
x = x.new_ones([2, 3, 3], dtype=torch.double)
x

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=torch.float64)

In [68]:
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[[0.0932, 0.0927, 0.3397],
         [0.7727, 0.7566, 0.8728],
         [0.4222, 0.2253, 0.6991]],

        [[0.9072, 0.9474, 0.7429],
         [0.9423, 0.3484, 0.1744],
         [0.5004, 0.2038, 0.4294]]])

In [69]:
x.size()

torch.Size([2, 3, 3])

In [71]:
y = torch.ones(x.size())
y

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [72]:
x + y

tensor([[[1.0932, 1.0927, 1.3397],
         [1.7727, 1.7566, 1.8728],
         [1.4222, 1.2253, 1.6991]],

        [[1.9072, 1.9474, 1.7429],
         [1.9423, 1.3484, 1.1744],
         [1.5004, 1.2038, 1.4294]]])

In [73]:
torch.add(x, y)

tensor([[[1.0932, 1.0927, 1.3397],
         [1.7727, 1.7566, 1.8728],
         [1.4222, 1.2253, 1.6991]],

        [[1.9072, 1.9474, 1.7429],
         [1.9423, 1.3484, 1.1744],
         [1.5004, 1.2038, 1.4294]]])

In [74]:
sum = torch.rand(x.size())
torch.add(x, y, out=sum)
sum

tensor([[[1.0932, 1.0927, 1.3397],
         [1.7727, 1.7566, 1.8728],
         [1.4222, 1.2253, 1.6991]],

        [[1.9072, 1.9474, 1.7429],
         [1.9423, 1.3484, 1.1744],
         [1.5004, 1.2038, 1.4294]]])

In [75]:
sum.add_(y)

tensor([[[2.0932, 2.0927, 2.3397],
         [2.7727, 2.7566, 2.8728],
         [2.4222, 2.2253, 2.6991]],

        [[2.9072, 2.9474, 2.7429],
         [2.9423, 2.3484, 2.1744],
         [2.5004, 2.2038, 2.4294]]])

In [78]:
sum.copy_(y)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [82]:
c = torch.randn([3, 4])
c.t_()

tensor([[-2.4027, -0.3325,  1.7777],
        [-0.0625, -0.6794, -1.7783],
        [ 0.4358,  0.4976,  0.9426],
        [-0.8243,  1.0986, -0.5807]])

In [83]:
c

tensor([[-2.4027, -0.3325,  1.7777],
        [-0.0625, -0.6794, -1.7783],
        [ 0.4358,  0.4976,  0.9426],
        [-0.8243,  1.0986, -0.5807]])

In [87]:
c[:, 0:2]

tensor([[-2.4027, -0.3325],
        [-0.0625, -0.6794],
        [ 0.4358,  0.4976],
        [-0.8243,  1.0986]])

In [95]:
x = torch.randn(3, 4)
y = x.view(-1, 6)

In [103]:
z = torch.randn(1)
z

tensor([-1.7021])

In [104]:
z.item()

-1.7021324634552002

In [105]:
x

tensor([[ 8.8534e-01,  5.3240e-01, -3.9163e-01,  4.7403e-01],
        [-1.3526e+00, -7.8544e-01,  6.8176e-01,  1.1838e+00],
        [-4.8694e-02, -6.9193e-01, -1.6627e-01,  8.4862e-04]])

In [174]:
a = torch.randint(1, 6, (4, 5))

In [175]:
b = a.numpy()
b

array([[1, 5, 4, 4, 2],
       [5, 4, 4, 4, 2],
       [2, 2, 4, 5, 5],
       [4, 3, 1, 2, 1]], dtype=int64)

In [176]:
b = b.T
b

array([[1, 5, 2, 4],
       [5, 4, 2, 3],
       [4, 4, 4, 1],
       [4, 4, 5, 2],
       [2, 2, 5, 1]], dtype=int64)

In [177]:
a

tensor([[1, 5, 4, 4, 2],
        [5, 4, 4, 4, 2],
        [2, 2, 4, 5, 5],
        [4, 3, 1, 2, 1]])

In [185]:
a = np.random.randint(0, 10, [3, 4])
a

array([[1, 3, 1, 0],
       [7, 7, 3, 7],
       [4, 8, 9, 1]])

In [186]:
b = torch.from_numpy(a)
b

tensor([[1, 3, 1, 0],
        [7, 7, 3, 7],
        [4, 8, 9, 1]], dtype=torch.int32)

In [187]:
b.t_()
print(b)

tensor([[1, 7, 4],
        [3, 7, 8],
        [1, 3, 9],
        [0, 7, 1]], dtype=torch.int32)


In [188]:
a

array([[1, 3, 1, 0],
       [7, 7, 3, 7],
       [4, 8, 9, 1]])

In [189]:
np.add(a, 10, out=a)

array([[11, 13, 11, 10],
       [17, 17, 13, 17],
       [14, 18, 19, 11]])

In [190]:
b

tensor([[11, 17, 14],
        [13, 17, 18],
        [11, 13, 19],
        [10, 17, 11]], dtype=torch.int32)

In [193]:
torch.cuda.is_available()

False

In [195]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [199]:
y = x + 1
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [203]:
y.grad_fn

In [216]:
z = y**2 * 3
out = z.mean()
out

tensor(12., grad_fn=<MeanBackward0>)

In [217]:
z.grad_fn

In [220]:
a = torch.randn(2, 2)
a.requires_grad_(True)

tensor([[ 0.1423,  0.5775],
        [-1.1817,  0.4627]], requires_grad=True)

In [226]:
b = torch.matmul(a, a).sum()
b.grad_fn

In [230]:
x = torch.randn(2, 3, requires_grad=True)
y = x + 1
z = y**2 * 3
out = z.mean()

In [232]:
out.grad_fn

In [233]:
out.backward()

In [264]:
from torch.autograd import Variable
x = Variable(torch.randn(2, 3), requires_grad=True)
x

tensor([[-0.8050, -0.3913,  1.7207],
        [ 0.8072,  0.5647, -2.2026]], requires_grad=True)

In [265]:
y = x + 3
z = torch.matmul(x, torch.t(y))
out = z.sum()

In [266]:
out.backward()

In [267]:
x.grad

tensor([[6.0045, 6.3467, 5.0361],
        [6.0045, 6.3467, 5.0361]])

In [268]:
type(x)

torch.Tensor

In [269]:
x.type()

'torch.FloatTensor'

In [277]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
out = y.mean()

In [278]:
out.backward()

In [279]:
x.grad

tensor([2.])

In [3]:
import time

x = torch.randn(10000, 10000)
y = torch.randn(10000, 10000)

start_time = time.clock()
z1 = torch.mul(x, y)
end_time = time.clock()
print(end_time-start_time)

x1 = x.cuda()
y1 = y.cuda()

start_time = time.clock()
z1 = torch.mul(x1, y1)
end_time = time.clock()
print(end_time-start_time)

0.1311708747341869
0.06834739056578254


In [4]:
torch.cuda.is_available()

True