In [1]:
import torch

In [4]:
#tensor 与numpy 类似
x= torch.empty(5,3)
print(x)               #输出一个未初始化的矩阵

tensor([[5.8855e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.2948e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
x=torch.rand(4,2)
print(x)                #输出一个随机初始化的矩阵

tensor([[0.8940, 0.7068],
        [0.3190, 0.7277],
        [0.7156, 0.5120],
        [0.9176, 0.4257]])


In [7]:
x= torch.zeros(9,4,dtype = torch.long)
print(x)               #构建一个指定类型的全零矩阵

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [8]:
x= torch.tensor([[1,2],
                [3,4]])
print(x)                   #直接构建给定的矩阵

tensor([[1, 2],
        [3, 4]])


In [11]:
# 基于存在的矩阵构建矩阵
x= torch.ones(5,3,dtype=torch.double)
print(x)
y=torch.rand_like(x,dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.3832, 0.8656, 0.3864],
        [0.5323, 0.7087, 0.0353],
        [0.5768, 0.6625, 0.7421],
        [0.6483, 0.6932, 0.9604],
        [0.2241, 0.2615, 0.7546]])


In [12]:
#型号？
x.size()

torch.Size([5, 3])

In [ ]:
#torch.Size 是元组，所以支持元组的所有操作

In [17]:
c=torch.rand(5,3)
print(c)
print(y+c)         #当y,c不相同时，不能相加

tensor([[0.2527, 0.7476, 0.3509],
        [0.5930, 0.3191, 0.2139],
        [0.8033, 0.9844, 0.3410],
        [0.6127, 0.9617, 0.2486],
        [0.8758, 0.1481, 0.1172]])
tensor([[0.6359, 1.6131, 0.7373],
        [1.1253, 1.0278, 0.2492],
        [1.3801, 1.6468, 1.0831],
        [1.2610, 1.6549, 1.2090],
        [1.0999, 0.4097, 0.8718]])


In [18]:
#另一种相加的方式
print(torch.add(y,c))

tensor([[0.6359, 1.6131, 0.7373],
        [1.1253, 1.0278, 0.2492],
        [1.3801, 1.6468, 1.0831],
        [1.2610, 1.6549, 1.2090],
        [1.0999, 0.4097, 0.8718]])


In [25]:
result =torch.empty(0,0)
torch.add(y,c,out =result)
print(result)                #经测验，empty中的（n,m）取值不影响结果

tensor([[0.6359, 1.6131, 0.7373],
        [1.1253, 1.0278, 0.2492],
        [1.3801, 1.6468, 1.0831],
        [1.2610, 1.6549, 1.2090],
        [1.0999, 0.4097, 0.8718]])


In [27]:
#in_place 计算
y.add_(c)
#在位计算后加  _

tensor([[0.6359, 1.6131, 0.7373],
        [1.1253, 1.0278, 0.2492],
        [1.3801, 1.6468, 1.0831],
        [1.2610, 1.6549, 1.2090],
        [1.0999, 0.4097, 0.8718]])

In [29]:
#索引与numpy类似
b=c[:,2]
b

tensor([0.3509, 0.2139, 0.3410, 0.2486, 0.1172])

In [32]:
# resize
x=torch.randn(4,4)
y = x.view(16)
z=y.view(-1,8)         #-1的意思是 向量最终维数取决于后者 8
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [34]:
#使用。item 将元素转化为Python量
x=torch.empty(1)
y=x.item()
print(x)
print(y)

tensor([-7.2156e+11])
-721557651456.0


# numpy 和tensor 之间的转换
1.tensor to numpy

In [36]:
x= torch.ones(5)
print(x)
x.numpy()
print(x)
b=x.numpy()
print(b)                     #说明前一种情况不改变X的原值

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [37]:
x.add_(1)
print(x)
print(b)                      #说明b是指向x的，x改变，b亦改变

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# 2.numpy to tensor

In [2]:
import numpy as np
a= np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [40]:
np.add(b,1,out=a)

array([2., 2., 2., 2., 2.])

In [41]:
a

array([2., 2., 2., 2., 2.])

In [42]:
b                            

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [46]:
print(b.size())    
np.add(a,1,out =a)               # 发现了吗？   b是Tensor， 但用numpy去改变b,a也改变了  out 只能是a，说明out得是 array

torch.Size([5])


array([4., 4., 4., 4., 4.])

In [5]:
a=np.ones(5)
b=torch.ones(4)
print(a)
print(a.dtype)
list(b.size())

[1. 1. 1. 1. 1.]
float64


[4]

In [ ]:
# CUDA tensors
#这里暂且搁置                 #询问CUDA的功能和用途

In [3]:
torch.cuda.is_available()

False

# AutoGrad

In [ ]:
#先放下，看完autograd 写总结
# 当给定的tensor的requires_grad 是True的时候，这个tensor的计算将被追踪。

In [22]:
x =torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [23]:
print(x.data)

tensor([[1., 1.],
        [1., 1.]])


In [24]:
print(x.grad)

None


In [25]:
print(x.grad_fn)

None


In [26]:
y=x+2
print(y)
print(y.grad)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
None


In [11]:
print(y.grad_fn)

In [12]:
z=y*3
print(z)
print(z.grad_fn)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)


In [27]:
y=y*6
print(y)
print(y.grad_fn)


tensor([[18., 18.],
        [18., 18.]], grad_fn=<MulBackward0>)


In [28]:
y=x+2
z= y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [21]:
a = torch.rand(2,2)
a =(a*3)/(a-1)
print("when no True:")
print(a.requires_grad)
print(a.grad)
print(a.grad_fn)
a.requires_grad_(True)
print("when True:")
print(a.requires_grad)
print(a.grad)
print(a.grad_fn)
b=(a*a).sum()
print("when b:")
print(b.requires_grad)
print(b.grad,"?")
print(b.grad_fn,"+")

when no True:
False
None
None
when True:
True
None
None
when b:
True
None ?
<SumBackward0 object at 0x0000000005555B38> +


In [60]:
# 没看懂为什么最后是4.5，也就是说和是18，那应该是（x+2）*6，为什么？ 
#这个计算有个很有意思的点，最后除以n*m，为什么不放在中间？
x =torch.ones(2,2,requires_grad=True)
y=x+2
print("y:",y)
z= y*y*3
out = z.mean()
print(z)
print(out.size)
print("out:",out)
out.backward()
print(x.grad)

y: tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
<built-in method size of Tensor object at 0x00000000055B6B40>
out: tensor(27., grad_fn=<MeanBackward1>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [52]:
x=torch.tensor([[4,6],
               [10,12]],dtype=torch.float)
z=x.mean()
print(z)

tensor(8.)


In [59]:
x=torch.ones(3,3,requires_grad=True)
z=x+1
print(z)
out= z.mean()
print(out)
out.backward()
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], grad_fn=<AddBackward0>)
tensor(2., grad_fn=<MeanBackward1>)
tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])


In [67]:
x=torch.ones(2,3,requires_grad=True)
y = x + 2
z = y * y * 5
out = z.mean()
#z.backward() #出错，RuntimeError: grad can be implicitly created only for scalar outputs
out.backward()
print(out)
print(x.grad)
# 多次运行该段程序，x.grad会每次增大5，out不变。为什么？

tensor(45., grad_fn=<MeanBackward1>)
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [69]:
x=torch.ones(2,2,requires_grad =True)
z= x+2
z=z.mean()
z.backward()            #说明backward只能是标量输出

In [73]:
x=torch.ones(2,2,requires_grad=True)
y= x+2
y.backward(torch.ones(2,2),retain_graph=True)           #这一步的作用是什么？
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [74]:
z=y*y
print(z)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)


In [76]:
gradient = torch.randn(2,2)
print("gradient:",gradient)
y.backward(gradient)                       #这一步的运行原理是什么？
print(x.grad)


gradient: tensor([[-0.2301, -1.2776],
        [-0.2416, -0.2475]])
tensor([[ 0.6527,  0.6595],
        [ 0.6687, -0.7312]])
